# Generated by Django 4.2 on 2024-09-13 19:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カードブランド')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('和食', '和食'), ('中華', '中華'), ('イタリアン', 'イタリアン'), ('フレンチ', 'フレンチ'), ('寿司', '寿司'), ('焼肉', '焼肉'), ('韓国料理', '韓国料理'), ('タイ料理', 'タイ料理'), ('スペイン料理', 'スペイン料理'), ('海鮮', '海鮮'), ('洋食', '洋食'), ('バー', 'バー'), ('ハンバーガー', 'ハンバーガー'), ('スイーツ', 'スイーツ'), ('カレー', 'カレー'), ('鉄板焼き/お好み', '鉄板焼き/お好み'), ('ラーメン', 'ラーメン'), ('ベーカリー', 'ベーカリー'), ('串/揚げ物', '串/揚げ物'), ('カフェ', 'カフェ'), ('その他', 'その他')], max_length=50, null=True, verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='WantPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=40, verbose_name='行きたいお店')),
                ('web_site', models.URLField(blank=True, verbose_name='お店のURL')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='一言コメント')),
                ('visited', models.BooleanField(default=False, verbose_name='行った！')),
                ('revisit', models.BooleanField(default=False, verbose_name='リピあり！')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '行きたいとこリスト',
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=40, verbose_name='店舗名')),
                ('store_detail', models.TextField(blank=True, null=True, verbose_name='店舗詳細')),
                ('store_address', models.TextField(blank=True, null=True, verbose_name='店舗住所')),
                ('photo1', models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='写真1')),
                ('photo2', models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='写真2')),
                ('photo3', models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='写真3')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('photo1_compressed', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo2_compressed', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo3_compressed', models.ImageField(blank=True, null=True, upload_to='')),
                ('holiday', models.CharField(blank=True, choices=[('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('日', '日'), ('不定休', '不定休'), ('なし', 'なし'), ('臨時休業', '臨時休業')], max_length=10, null=True, verbose_name='定休日1')),
                ('holiday2', models.CharField(blank=True, choices=[('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('日', '日'), ('不定休', '不定休'), ('なし', 'なし'), ('臨時休業', '臨時休業')], max_length=10, null=True, verbose_name='定休日2')),
                ('holiday3', models.CharField(blank=True, choices=[('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('日', '日'), ('不定休', '不定休'), ('なし', 'なし'), ('臨時休業', '臨時休業')], max_length=10, null=True, verbose_name='定休日3')),
                ('irregular', models.CharField(blank=True, max_length=200, null=True, verbose_name='不定休の場合は備考を記入してください。')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gourmet.category', verbose_name='ジャンル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'StoreInfo',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=1)),
                ('handle', models.CharField(max_length=50, verbose_name='ニックネーム')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='レビュー内容')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('review_photo1', models.ImageField(blank=True, upload_to='reviews/', verbose_name='レビュー写真1')),
                ('review_photo2', models.ImageField(blank=True, upload_to='reviews/', verbose_name='レビュー写真2')),
                ('review_photo3', models.ImageField(blank=True, upload_to='reviews/', verbose_name='レビュー写真3')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gourmet.storeinfo', verbose_name='店名')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='予約日')),
                ('time', models.TimeField(verbose_name='予約時間')),
                ('persons', models.IntegerField(verbose_name='予約人数')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gourmet.storeinfo', verbose_name='店名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Mypage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=40, verbose_name='お店の名前')),
                ('store_address', models.CharField(blank=True, max_length=40, null=True, verbose_name='お店の場所')),
                ('feeling', models.TextField(blank=True, max_length=70, null=True, verbose_name='お店の感想')),
                ('photo1', models.ImageField(upload_to='', verbose_name='写真1(必須)')),
                ('photo2', models.ImageField(blank=True, upload_to='', verbose_name='写真2')),
                ('photo3', models.ImageField(blank=True, upload_to='', verbose_name='写真3')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gourmet.category', verbose_name='ジャンル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'マイページ',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last4', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='カード情報が正しくありません。', regex='^\\d{14,16}$')])),
                ('exp_month', models.PositiveIntegerField(choices=[('', '月'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], verbose_name='月')),
                ('exp_year', models.PositiveBigIntegerField(choices=[('', '年'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043')], verbose_name='年')),
                ('cardholder', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='大文字のアルファベットを入力してください。', regex='^[A-Z\\s]+$')], verbose_name='カード名義')),
                ('card_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gourmet.cardbrand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('fav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gourmet.storeinfo', verbose_name='お気に入り店舗')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_member'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'fav'), name='unique_user_fav'),
        ),
    ]
