# Generated by Django 4.2 on 2024-09-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='photo1_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='photo2_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='photo3_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
