# Generated by Django 4.2 on 2024-09-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinfo',
            name='photo1_compressed',
        ),
        migrations.RemoveField(
            model_name='storeinfo',
            name='photo2_compressed',
        ),
        migrations.RemoveField(
            model_name='storeinfo',
            name='photo3_compressed',
        ),
    ]
