# Generated by Django 4.2 on 2024-09-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0002_alter_storeinfo_photo1_compressed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinfo',
            name='photo1_compressed',
        ),
        migrations.RemoveField(
            model_name='storeinfo',
            name='photo2_compressed',
        ),
        migrations.RemoveField(
            model_name='storeinfo',
            name='photo3_compressed',
        ),
    ]
