# Generated by Django 4.2 on 2024-09-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0003_remove_storeinfo_photo1_compressed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypage',
            name='photo1_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mypage',
            name='photo2_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mypage',
            name='photo3_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='photo1_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='photo2_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='photo3_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
