# Generated by Django 4.2 on 2024-09-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0003_storeinfo_photo1_compressed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypage',
            name='photo1_mycompressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mypage',
            name='photo2_mycompressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mypage',
            name='photo3_mycompressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
