# Generated by Django 4.2 on 2024-09-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0004_mypage_photo1_compressed_mypage_photo2_compressed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypage',
            old_name='photo1_compressed',
            new_name='photo1_mycompressed',
        ),
        migrations.RenameField(
            model_name='mypage',
            old_name='photo2_compressed',
            new_name='photo2_mycompressed',
        ),
        migrations.RenameField(
            model_name='mypage',
            old_name='photo3_compressed',
            new_name='photo3_mycompressed',
        ),
    ]
