# Generated by Django 4.2 on 2024-09-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0004_mypage_photo1_mycompressed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo1_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='photo2_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='photo3_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
