# Generated by Django 4.2 on 2024-09-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0005_review_photo1_compressed_review_photo2_compressed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='store_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='店舗メールアドレス'),
        ),
    ]
