# Generated by Django 4.2 on 2024-09-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0005_rename_photo1_compressed_mypage_photo1_mycompressed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypage',
            name='photo1_mycompressed',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='photo2_mycompressed',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='photo3_mycompressed',
        ),
    ]
