# Generated by Django 4.2 on 2024-09-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0007_storeinfo_store_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='予約完了'),
        ),
    ]
