# Generated by Django 4.2 on 2024-09-23 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gourmet', '0008_reservation_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='来店済み'),
        ),
        migrations.CreateModel(
            name='Stripe_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeCustomerId', models.CharField(max_length=255, verbose_name='stipe顧客ID')),
                ('stripeSubscriptionId', models.CharField(max_length=255, verbose_name='stripeサブスクID')),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
