# Generated by Django 4.2 on 2024-09-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0009_alter_reservation_is_visible_stripe_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripe_customer',
            options={'verbose_name_plural': 'stripeサブスク会員'},
        ),
    ]
