# Generated by Django 4.2 on 2024-07-08 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0010_alter_reservation_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='星の数(1~5)で評価')),
                ('handle', models.CharField(max_length=50, verbose_name='ニックネーム')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='レビュー内容')),
                ('photo1', models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='投稿写真1')),
                ('photo2', models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='投稿写真2')),
                ('photo3', models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='投稿写真3')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gourmet.storeinfo', verbose_name='店名')),
            ],
        ),
    ]
