# Generated by Django 4.2 on 2024-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='review',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='review',
            name='photo3',
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.CharField(choices=[('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★')], max_length=1, verbose_name='お店の評価'),
        ),
    ]
