# Generated by Django 4.2 on 2024-07-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0012_remove_review_photo1_remove_review_photo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
    ]
