# Generated by Django 4.2 on 2024-07-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0013_remove_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
