# Generated by Django 4.2 on 2024-08-03 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gourmet', '0017_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('1', '和食'), ('2', '中華'), ('3', 'イタリアン'), ('4', 'フレンチ'), ('5', '寿司'), ('6', '焼肉'), ('7', '韓国料理'), ('8', 'タイ料理')], max_length=50, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
