# Generated by Django 4.2 on 2024-08-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0018_alter_category_category_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('和食', '和食'), ('中華', '中華'), ('イタリアン', 'イタリアン'), ('フレンチ', 'フレンチ'), ('寿司', '寿司'), ('焼肉', '焼肉'), ('韓国料理', '韓国料理')], max_length=50, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gourmet.category', verbose_name='ジャンル'),
        ),
    ]
