# Generated by Django 4.2 on 2024-08-11 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gourmet', '0019_alter_category_category_alter_storeinfo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カードブランド')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('和食', '和食'), ('中華', '中華'), ('イタリアン', 'イタリアン'), ('フレンチ', 'フレンチ'), ('寿司', '寿司'), ('焼肉', '焼肉'), ('韓国料理', '韓国料理'), ('タイ料理', 'タイ料理'), ('スペイン料理', 'スペイン料理')], max_length=50, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gourmet.category', verbose_name='ジャンル'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.PositiveIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], help_text='カードの有効期限月を選択してください。', verbose_name='有効期限月')),
                ('exp_year', models.PositiveBigIntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043')], help_text='カードの有効期限の年を選択してください。', verbose_name='有効期限年')),
                ('card_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gourmet.cardbrand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
