# Generated by Django 4.2 on 2024-08-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0021_alter_category_category_alter_member_exp_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cardholder',
            field=models.CharField(max_length=50, null=True, verbose_name='カード名義'),
        ),
    ]
