# Generated by Django 4.2 on 2024-08-11 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0022_member_cardholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cardholder',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='大文字のアルファベットを入力してください。', regex='^[A-Z\\s]+$')], verbose_name='カード名義'),
        ),
        migrations.AlterField(
            model_name='member',
            name='exp_month',
            field=models.PositiveIntegerField(choices=[('', '月'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='member',
            name='exp_year',
            field=models.PositiveBigIntegerField(choices=[('', '年'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043')], verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last4',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='カード情報が正しくありません。', regex='^\\d{14,16}$')]),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_member'),
        ),
    ]
