# Generated by Django 4.2 on 2024-08-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0023_alter_member_cardholder_alter_member_exp_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='store_address',
            field=models.TextField(blank=True, null=True, verbose_name='店舗住所'),
        ),
    ]
