# Generated by Django 4.2 on 2024-08-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0024_storeinfo_store_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('和食', '和食'), ('中華', '中華'), ('イタリアン', 'イタリアン'), ('フレンチ', 'フレンチ'), ('寿司', '寿司'), ('焼肉', '焼肉'), ('韓国料理', '韓国料理'), ('タイ料理', 'タイ料理'), ('スペイン料理', 'スペイン料理'), ('海鮮', '海鮮')], max_length=50, null=True, verbose_name='ジャンル'),
        ),
    ]
