# Generated by Django 4.2 on 2024-08-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0025_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('和食', '和食'), ('中華', '中華'), ('イタリアン', 'イタリアン'), ('フレンチ', 'フレンチ'), ('寿司', '寿司'), ('焼肉', '焼肉'), ('韓国料理', '韓国料理'), ('タイ料理', 'タイ料理'), ('スペイン料理', 'スペイン料理'), ('海鮮', '海鮮'), ('洋食', '洋食'), ('バー', 'バー'), ('ハンバーガー', 'ハンバーガー'), ('スイーツ', 'スイーツ'), ('カレー', 'カレー'), ('鉄板焼き/お好み焼き', '鉄板焼き/お好み焼き')], max_length=50, null=True, verbose_name='ジャンル'),
        ),
    ]
