# Generated by Django 4.2 on 2024-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0028_alter_category_category_alter_storeinfo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_photo1',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='レビュー写真1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('和食', '和食'), ('中華', '中華'), ('イタリアン', 'イタリアン'), ('フレンチ', 'フレンチ'), ('寿司', '寿司'), ('焼肉', '焼肉'), ('韓国料理', '韓国料理'), ('タイ料理', 'タイ料理'), ('スペイン料理', 'スペイン料理'), ('海鮮', '海鮮'), ('洋食', '洋食'), ('バー', 'バー'), ('ハンバーガー', 'ハンバーガー'), ('スイーツ', 'スイーツ'), ('カレー', 'カレー'), ('鉄板焼き/お好み', '鉄板焼き/お好み'), ('ラーメン', 'ラーメン'), ('その他(ベーカリー)', 'その他(ベーカリー)'), ('串/揚げ物', '串/揚げ物')], max_length=50, null=True, verbose_name='ジャンル'),
        ),
    ]
