# Generated by Django 4.2 on 2024-08-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0029_review_review_photo1_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_photo2',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='reviews/', verbose_name='レビュー写真2'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_photo3',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='reviews/', verbose_name='レビュー写真3'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_photo1',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='reviews/', verbose_name='レビュー写真1'),
        ),
    ]
