# Generated by Django 4.2 on 2024-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0030_review_review_photo2_review_review_photo3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_photo1',
            field=models.ImageField(blank=True, upload_to='reviews/', verbose_name='レビュー写真1'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_photo2',
            field=models.ImageField(blank=True, upload_to='reviews/', verbose_name='レビュー写真2'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_photo3',
            field=models.ImageField(blank=True, upload_to='reviews/', verbose_name='レビュー写真3'),
        ),
    ]
