# Generated by Django 4.2 on 2024-08-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0033_review_review_photo1_review_review_photo2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewPhoto',
        ),
    ]
