# Generated by Django 4.2 on 2024-08-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0034_delete_reviewphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_photo1',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_photo2',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_photo3',
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_photos/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gourmet.review')),
            ],
        ),
    ]
