# Generated by Django 4.2 on 2024-08-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0036_review_review_photo1_review_review_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='holiday',
            field=models.CharField(blank=True, choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')], max_length=10, null=True, verbose_name='定休日'),
        ),
    ]
