# Generated by Django 4.2 on 2024-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0040_storeinfo_holiday2_alter_storeinfo_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='holiday3',
            field=models.CharField(blank=True, choices=[('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('日', '日'), ('不定休', '不定休'), ('なし', 'なし')], max_length=10, null=True, verbose_name='定休日3'),
        ),
    ]
