# Generated by Django 4.2 on 2024-08-30 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gourmet', '0041_storeinfo_holiday3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='holiday',
            field=models.CharField(blank=True, choices=[('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('日', '日'), ('不定休', '不定休'), ('なし', 'なし'), ('臨時休業', '臨時休業')], max_length=10, null=True, verbose_name='定休日1'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='holiday2',
            field=models.CharField(blank=True, choices=[('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('日', '日'), ('不定休', '不定休'), ('なし', 'なし'), ('臨時休業', '臨時休業')], max_length=10, null=True, verbose_name='定休日2'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='holiday3',
            field=models.CharField(blank=True, choices=[('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('日', '日'), ('不定休', '不定休'), ('なし', 'なし'), ('臨時休業', '臨時休業')], max_length=10, null=True, verbose_name='定休日3'),
        ),
        migrations.CreateModel(
            name='Mypage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=40, verbose_name='店舗名')),
                ('store_address', models.TextField(blank=True, null=True, verbose_name='お店の場所')),
                ('feeling', models.TextField(blank=True, null=True, verbose_name='お店の感想')),
                ('photo1', models.ImageField(blank=True, upload_to='', verbose_name='写真1')),
                ('photo2', models.ImageField(blank=True, upload_to='', verbose_name='写真2')),
                ('photo3', models.ImageField(blank=True, upload_to='', verbose_name='写真3')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gourmet.category', verbose_name='ジャンル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'マイページ',
            },
        ),
    ]
