# Generated by Django 4.2 on 2024-08-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0041_storeinfo_holiday3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='holiday',
            field=models.CharField(blank=True, choices=[('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('日', '日'), ('不定休', '不定休'), ('なし', 'なし'), ('臨時休業', '臨時休業')], max_length=10, null=True, verbose_name='定休日1'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='holiday2',
            field=models.CharField(blank=True, choices=[('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('日', '日'), ('不定休', '不定休'), ('なし', 'なし'), ('臨時休業', '臨時休業')], max_length=10, null=True, verbose_name='定休日2'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='holiday3',
            field=models.CharField(blank=True, choices=[('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('日', '日'), ('不定休', '不定休'), ('なし', 'なし'), ('臨時休業', '臨時休業')], max_length=10, null=True, verbose_name='定休日3'),
        ),
    ]
