# Generated by Django 4.2 on 2024-09-02 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gourmet', '0042_alter_storeinfo_holiday_alter_storeinfo_holiday2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('和食', '和食'), ('中華', '中華'), ('イタリアン', 'イタリアン'), ('フレンチ', 'フレンチ'), ('寿司', '寿司'), ('焼肉', '焼肉'), ('韓国料理', '韓国料理'), ('タイ料理', 'タイ料理'), ('スペイン料理', 'スペイン料理'), ('海鮮', '海鮮'), ('洋食', '洋食'), ('バー', 'バー'), ('ハンバーガー', 'ハンバーガー'), ('スイーツ', 'スイーツ'), ('カレー', 'カレー'), ('鉄板焼き/お好み', '鉄板焼き/お好み'), ('ラーメン', 'ラーメン'), ('ベーカリー', 'ベーカリー'), ('串/揚げ物', '串/揚げ物'), ('カフェ', 'カフェ'), ('その他', 'その他')], max_length=50, null=True, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='feeling',
            field=models.TextField(blank=True, max_length=70, null=True, verbose_name='お店の感想'),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='photo1',
            field=models.ImageField(upload_to='', verbose_name='写真1(必須)'),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='store_address',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='お店の場所'),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='store_name',
            field=models.CharField(max_length=40, verbose_name='お店の名前'),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.CreateModel(
            name='WantPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=40, verbose_name='行きたいお店の名前')),
                ('web_site', models.URLField(blank=True, verbose_name='お店のURL')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='一言コメント')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '行きたいとこリスト',
            },
        ),
    ]
