# Generated by Django 4.2 on 2024-09-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0043_alter_category_category_alter_mypage_feeling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantplace',
            name='revisit',
            field=models.BooleanField(default=False, verbose_name='リピあり！'),
        ),
        migrations.AddField(
            model_name='wantplace',
            name='visited',
            field=models.BooleanField(default=False, verbose_name='行った！'),
        ),
        migrations.AlterField(
            model_name='wantplace',
            name='store_name',
            field=models.CharField(max_length=40, verbose_name='行きたいお店'),
        ),
    ]
