# Generated by Django 4.2 on 2024-09-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0044_wantplace_revisit_wantplace_visited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='photo1_compressed',
            field=models.ImageField(blank=True, null=True, upload_to='photos/compressed/'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='photo2_compressed',
            field=models.ImageField(blank=True, null=True, upload_to='photos/compressed/'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='photo3_compressed',
            field=models.ImageField(blank=True, null=True, upload_to='photos/compressed/'),
        ),
    ]
