# Generated by Django 4.2 on 2024-07-08 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='furigana',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator('^[ァ-ヶー]+$', 'カタカナで入力してください。')], verbose_name='フリガナ*スペースなし'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='正しい電話番号の形式で入力してください（例: 090-1234-5678）。', regex='^\\d{2,4}-\\d{2,4}-\\d{4}$')], verbose_name='電話番号（例: 090-1234-5678）'),
        ),
    ]
