# Generated by Django 4.2 on 2024-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_furigana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='handle',
            field=models.CharField(default='', max_length=50, verbose_name='ニックネーム'),
        ),
    ]
